version: '3.8'

services:
  # Frontend Service
  dreamvacationsfrontend:
    image: dreamvacationsfrontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --openssl-legacy-provider  # <-- Add this line
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules

  # Database Service
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
